### ISSUE TITLE
timezone problems while running tests

### ISSUE THREAD

**Issue by jensens** [plone/plone.dexterity#26]
While running coredev5 with ``bin/alltests`` on my machine I get the following errors; it seems there is a timezone problem somewhere in tests or code. My machine is configured in Europe/Vienna timezone.

    Failure in test test_item_dublincore (plone.dexterity.tests.test_content.TestContent)
    Traceback (most recent call last):
      File "/usr/lib/python2.7/unittest/case.py", line 331, in run
        testMethod()
      File "/home/jensens/.buildout/shared-eggs/mocker-1.1.1-py2.7.egg/mocker.py", line 149, in test_method_wrapper
        result = test_method()
      File "/home/jensens/workspace/coredev5/src/plone.dexterity/plone/dexterity/tests/test_content.py", line 682, in test_item_dublincore
        i.ModificationDate()[:19], i.modification_date.ISO()[:19])
      File "/usr/lib/python2.7/unittest/case.py", line 515, in assertEqual
        assertion_func(first, second, msg=msg)
      File "/usr/lib/python2.7/unittest/case.py", line 508, in _baseAssertEqual
        raise self.failureException(msg)
    AssertionError: '2014-05-31T23:00:00' != '2014-06-01T00:00:00'

        551/1472 (37.4%)

    Failure in test test_item_dublincore_date (plone.dexterity.tests.test_content.TestContent)
    Traceback (most recent call last):
      File "/usr/lib/python2.7/unittest/case.py", line 331, in run
        testMethod()
      File "/home/jensens/.buildout/shared-eggs/mocker-1.1.1-py2.7.egg/mocker.py", line 149, in test_method_wrapper
        result = test_method()
      File "/home/jensens/workspace/coredev5/src/plone.dexterity/plone/dexterity/tests/test_content.py", line 724, in test_item_dublincore_date
        i.ModificationDate()[:19], i.modification_date.ISO()[:19])
      File "/usr/lib/python2.7/unittest/case.py", line 515, in assertEqual
        assertion_func(first, second, msg=msg)
      File "/usr/lib/python2.7/unittest/case.py", line 508, in _baseAssertEqual
        raise self.failureException(msg)
    AssertionError: '2014-05-31T23:00:00' != '2014-06-01T00:00:00'

        552/1472 (37.5%)

    Failure in test test_item_dublincore_datetime (plone.dexterity.tests.test_content.TestContent)
    Traceback (most recent call last):
      File "/usr/lib/python2.7/unittest/case.py", line 331, in run
        testMethod()
      File "/home/jensens/.buildout/shared-eggs/mocker-1.1.1-py2.7.egg/mocker.py", line 149, in test_method_wrapper
        result = test_method()
      File "/home/jensens/workspace/coredev5/src/plone.dexterity/plone/dexterity/tests/test_content.py", line 774, in test_item_dublincore_datetime
        self.assertEqual(i.ModificationDate(), i.modification_date.ISO())
      File "/usr/lib/python2.7/unittest/case.py", line 515, in assertEqual
        assertion_func(first, second, msg=msg)
      File "/usr/lib/python2.7/unittest/case.py", line 508, in _baseAssertEqual
        raise self.failureException(msg)
    AssertionError: '2014-05-31T23:00:00+01:00' != '2014-06-01T00:00:00+02:00'

**Comment by jensens** [comment]
now this works, no idea why
